server:
  port: 8080
  servlet:
    context-path: /biblioteca/core/
  compression:
    enabled: true
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:h2:mem:core
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
      database-plataform: org.hibernate.dialect.H2Dialect
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123
    exchanges:
      direct:
        name: amq.direct
    queues:
      biblioteca:
        name: biblioteca
      criar-agenda:
        name: criar-agenda
      deletar-agenda:
        name: deletar-agenda
  h2:
    console:
      enabled: true
      path: /h2-core

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE